unepwcmc/ProtectedPlanet

app/assets/javascripts/modules/maps/base.js.coffee, app/assets/javascripts/modules/maps/interactive.js.coffee, app/assets/javascripts/modules/maps/protected_area_overlay.js.coffee, app/assets/javascripts/modules/protected_areas/base.js.coffee, app/assets/javascripts/modules/tabs.js.coffee, app/views/protected_areas/_map.html.erb
mob #1
Mob 2
Mob3
Mob 4
mob5
Mob6
mob4
Mob 7
mob 8
Mob9
Mob 10
=> Add map to PA page (mob programming!🎉)

app/assets/javascripts/modules/maps/base.js.coffee, app/assets/javascripts/modules/protected_areas/base.js.coffee, app/controllers/api/v3/networks_controller.rb, app/models/network.rb, app/views/protected_areas/_map.html.erb, config/routes.rb
Updates bounds when selecting network
=> New site page network bounds

app/assets/javascripts/modules/fullscreen.js.coffee, app/assets/javascripts/modules/maps/base.js.coffee, app/assets/javascripts/modules/protected_areas/base.js.coffee, app/assets/javascripts/protected_areas.js, app/views/layouts/application.html.erb, app/views/protected_areas/_map_connections.html.erb, app/views/protected_areas/_map_site.html.erb
- Add fullscreen button to both maps
- Style
- Make sure leaflet js renders the map at the correct size when the button is clicked
=> Map fullscreen

app/assets/javascripts/modules/maps/base.js.coffee
Getting the geojson from our db can be too expensive and load up the system.
Here I'm getting the data from cartodb instead.
=> Get geojson from cartodb instead of our own db to improve performance

app/controllers/marine_controller.rb, app/models/protected_area.rb, app/presenters/country_presenter.rb, app/presenters/protected_area_presenter.rb
Calculate stats for the marine page and format those that are static
=> Generate stats for marine page

.gitmodules, config/secrets.yml
Point to the newest ESRI server. The link in the menu was pointing to the old one
=> Point to new ESRI server

app/views/marine/index.html.erb, app/views/marine/sections/_distribution.html.erb, app/views/marine/sections/_growth.html.erb
Statistics have been replaced with dynamic statistics.
=> Replaced static stats on marine page with dynamic stats

app/controllers/marine_controller.rb, app/views/marine/index.html.erb, app/views/marine/sections/_coverage_map.html.erb, app/views/marine/sections/_distribution.html.erb, app/views/marine/sections/_growth.html.erb, lib/data/seeds/marine_statistics.csv, lib/modules/wdpa/importer.rb, lib/modules/wdpa/marine_stats_importer.rb, test/unit/wdpa/importer_test.rb, test/unit/wdpa/marine_stats_importer_test.rb
I have made the necessary changes to import the marine statistics into Redis and retrieve them as a hash. However, I do feel like I could go further and I could consolidate the two different statistics methods in the controller into just one structure which has all of the necessary data.
=> Add marine stats importer

app/presenters/region_presenter.rb
I had to fix the `sources_per_jurisdiction_hash` like I did for my other pull request because I needed to get the page loading to fix this other issue. There might be an issue with merging. Anyway the percentages have been fixed now!
=> Fixed percentages for iucn management categories

app/views/region/_hero.html.erb, app/views/region/_info_box.html.erb
I have commented out the sections for the downloads. There might be a better more elegant way of commenting this out, but I went with the suggestion I found on Stack Overflow.
=> Temporarily disable downloads on region page

app/helpers/regions_helper.rb, app/views/region/facts/_related_countries.html.erb
It has been requested to show only countries (without overseas territories) for Europe.
I have added an helper to correctly retrieve the list of countries for the given region.
=> Add region helper to retrieve countries w/wo territories

app/models/region.rb
As requested, I have ordered the categories in the desired order.
=> Put iucn categories in the correct order

.travis.yml, CHANGELOG.md, app/presenters/statistic_presenter.rb, app/views/search/_country.html.erb
This is the initial work to fix the search results to correctly display the PA coverage total percentage.
=> Fixed search results to correctly display the pa coverage total percentage

CHANGELOG.md, app/helpers/protected_areas_helper.rb, app/models/pame_evaluation.rb, app/views/shared/stats/facts/_management_effectiveness.html.erb, lib/modules/wdpa/pame_importer.rb
- Renames 'method' to 'methodology' for PAME Evaluations to avoid reserved word hell
=> Release 2.1.4

test/unit/wdpa/green_list_importer_test.rb, test/unit/wdpa/importer_test.rb
## Description
* Add OverseasTerritoriesImporter to importer test
* Add GreenListImporter to importer test
* Add GreenListImporter test
=> Improve test coverage

lib/modules/import_tools.rb, lib/modules/wdpa/importer.rb
Added a monthly import helper to make importing the stats easier
=> Added monthly import helper

app/views/country/pdf/_info_box.html.erb, app/views/shared/_references.html.erb
Hello!
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that recommendation by updating static DOI links.
Cheers :-)
=> Link DOIs to preferred resolver

app/views/protected_areas/factsheet/_official_record.html.erb, app/views/shared/stats/facts/_management_effectiveness.html.erb, lib/data/seeds/story_map_link_sites.csv, lib/modules/wdpa/importer.rb, lib/modules/wdpa/story_map_link_list_importer.rb
- the second link (Arabic) is hardcoded for the moment
- the related migration is on the master branch of the submodule protectedplanet-db
Make sure to run the script `Wdpa::StoryMapLinkListImporter.import` in staging and production to populate the `story_map_link` attribute of ProtectedArea
=> Add story map section

docs/installation.md
This adds a certain error which may appear and how to fix it.
=> Initial work towards updating the documentation with regards to an error

CHANGELOG.md, lib/modules/wdpa/pame_importer.rb
(cherry picked from commit 66fe1409a9e2e456e6e6189b6a9f666ec10b1477)
This PR is the initial work to update the PP-PAME CSV for the latest monthly release.
=> Add the latest pame csv to the import data and import task

app/assets/stylesheets/charts/_chart-dial.scss, app/assets/stylesheets/charts/_chart-row-target.scss, app/assets/stylesheets/charts/_charts.scss, app/assets/stylesheets/resources/_base-variables.scss, app/javascript/components/charts/chart-row-target/ChartRowTarget.vue, app/javascript/vue.js, app/views/target_dashboard/index.html.erb
=> Create row target chart

app/assets/stylesheets/styles/components/_charts.scss, app/assets/stylesheets/styles/components/charts/_chart-dial.scss, app/assets/stylesheets/styles/components/charts/_chart-row-target.scss, app/javascript/components/charts/chart-dial/ChartDial.vue, app/javascript/components/charts/chart-row-target/ChartRowTarget.vue
=> T11 chart fixes

app/javascript/components/charts/chart-dial/ChartDial.vue, app/javascript/utilities/polyfill-find.js, app/javascript/vue.js, package.json, yarn.lock
=> T11 ie fixes

config/locales/thematic_area/target_11_dashboard/en.yml
=> update tooltip text

app/javascript/components/select/VSelectSearchable.vue, app/javascript/vue.js, app/views/layouts/application.html.erb, app/views/layouts/application/_head.html.erb, app/views/shared/_google_analytics.html.erb, package.json, yarn.lock
https://unep-wcmc.codebasehq.com/projects/pp-target-11-dashboard/tickets/36
Add google analytics event tracking.
=> Add event tracking when country/region is selected from the dropdown

app/assets/javascripts/content.js, app/assets/javascripts/modules/cms/base.js.coffee, app/assets/javascripts/modules/cms/tracked_download_links.js.coffee, app/views/shared/_google_analytics.html.erb, docs/installation.md
Production will need updating with data attributes for the tracked links. Then will need to check the events are working on ga and add the events to the list in codebase.
=> track oecm downloads

app/serializers/search/areas_serializer.rb, app/serializers/search/base_serializer.rb, app/serializers/search/full_serializer.rb, lib/modules/search/aggregators/model.rb
## Description
Simple PR to populate urls and make search results card redirect to corresponding page.
=> Refresh search cards urls

app/controllers/home_controller.rb, app/views/home/index.html.erb, app/views/layouts/partials/_hero-home.html.erb, config/locales/home/en.yml
Update home page hero.
Data to be provided later by CLS
=> Refresh home hero

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/components/_hero.scss, app/assets/stylesheets/components/cards/cards/_cards-resources.scss, app/helpers/application_helper.rb, app/presenters/resources_presenter.rb, app/views/partials/cards/_resources.html.erb
Complete [#16 - Component - Cards - Thematic areas](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/17) first.
Related ticket: https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/19
=> Refresh resources

app/assets/stylesheets/base/_base.scss, app/assets/stylesheets/base/_icons.scss, app/assets/stylesheets/base/mixins/_icons.scss, app/assets/stylesheets/base/mixins/_layout.scss, app/assets/stylesheets/components/_charts.scss, app/assets/stylesheets/components/cards/cards/_cards-scrollable.scss, app/assets/stylesheets/components/charts/_chart-row-pa.scss, app/assets/stylesheets/components/charts/_chart-row.scss, app/controllers/marine_controller.rb, app/javascript/components/charts/chart-bar/ChartBarSimple.vue, app/javascript/components/charts/chart-rectangles/ChartRectangles.vue, app/models/country_statistic.rb, app/presenters/country_presenter.rb, app/views/marine/index.html.erb, app/views/marine/sections/_coverage_map.html.erb, app/views/marine/sections/_national.html.erb, config/locales/thematic_area/marine/en.yml, test/factories/country_statistic.rb, test/models/country_statistic_test.rb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/99
=> Marine page - National chart

app/assets/stylesheets/components/_hero.scss, app/controllers/green_list_controller.rb, app/controllers/marine_controller.rb, app/models/protected_area.rb, app/views/green_list/index.html.erb, app/views/layouts/partials/_hero-thematic.html.erb, app/views/marine/index.html.erb, config/locales/thematic_area/green_list/en.yml, config/locales/thematic_area/marine/en.yml, lib/modules/stats/global.rb
Merge 377 first
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/43
=> Refresh marine hero

app/assets/stylesheets/components/cards/cards/_cards-articles.scss
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/14
=> Update font size of date in the news article cards

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/base/mixins/_text.scss, app/assets/stylesheets/components/_download.scss, app/assets/stylesheets/components/_hero.scss, app/assets/stylesheets/components/_tabs.scss, app/assets/stylesheets/components/cards/card/_card-theme.scss, app/assets/stylesheets/components/cards/cards/_cards-search-results-areas.scss, app/assets/stylesheets/components/charts/_chart-legend.scss, app/assets/stylesheets/helpers/_border-and-shadows.scss, app/controllers/country_controller.rb, app/javascript/components/charts/chart-line/ChartLegend.vue, app/javascript/components/charts/chart-line/ChartLine.vue, app/javascript/components/search/SearchAreas.vue, app/javascript/components/tabs/Tabs.vue, app/presenters/region_presenter.rb, app/views/country/show.html.erb, app/views/layouts/partials/_hero-area-types.html.erb, app/views/layouts/partials/_hero-thematic.html.erb, app/views/marine/index.html.erb, app/views/partials/bars/_topbar-secondary.html.erb, app/views/partials/cards/_articles.html.erb, app/views/partials/download/_download.html.erb
1. Pull the latest on the refresh branch in /db
2. import cms seeds
3. Amends are across the site and will be checked by Charlotte in the browser
=> Refresh design tweaks

app/views/marine/sections/_national.html.erb
Fix reference to flag svgs on the marine page
=> update reference to flag icons on the marine page

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/components/_nav.scss, app/assets/stylesheets/components/_topbar.scss, app/assets/stylesheets/components/search/_search-main.scss
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/49
=> Refresh nav

app/assets/stylesheets/components/cards/card/_card-stats.scss, app/views/partials/stats/_stats-overview.html.erb, app/views/protected_areas/show.html.erb, config/locales/stats/en.yml
=> Ticket 69 - Story Map Links

app/assets/stylesheets/components/_table.scss, config/locales/thematic_area/target_11_dashboard/en.yml
Edit text for thematical areas Aichi 11 page
http://localhost:3000/en/thematical-areas/global-partnership-on-aichi-target-11
=> Ticket 107

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_charts.scss, app/assets/stylesheets/components/cards/cards/_cards-resources.scss, app/assets/stylesheets/components/cards/cards/_cards-scrollable.scss, app/assets/stylesheets/components/charts/_chart-column.scss, app/assets/stylesheets/components/charts/_chart-legend.scss, app/assets/stylesheets/components/charts/_chart-row-pa.scss, app/assets/stylesheets/components/charts/_chart-row.scss, app/javascript/components/charts/chart-line/ChartLine.vue, app/javascript/components/charts/chart-row-pa/ChartRowPa.vue, app/presenters/region_presenter.rb, app/views/marine/sections/_coverage_growth.html.erb, app/views/marine/sections/_national.html.erb, app/views/marine/sections/_ocean.html.erb, app/views/partials/cards/_resources.html.erb, app/views/partials/ctas/_api.html.erb, app/views/partials/ctas/_live-report.html.erb, app/views/partials/stats/_stats-coverage.html.erb, config/locales/thematic_area/marine/en.yml
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/19
=> Ticket 19 & 24

app/assets/stylesheets/components/_nav.scss, app/assets/stylesheets/components/_topbar.scss, app/assets/stylesheets/components/search/_search-main.scss
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/49
=> Swap search and nav icon back over

app/assets/stylesheets/base/mixins/_text.scss, app/assets/stylesheets/components/_hero.scss
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/43
=> Update font sizes

app/javascript/components/map/mixins/mixin-pa-popup.js
There's some work on another branch that I will add to this once merged to fix the axios headers stuff.
Currently has option for requests in parallel commented out vs requests in sequence. Must be a neater way to do the sequence one's...
=> Refresh maps popup

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/cards/card/_card-stats.scss, app/assets/stylesheets/components/maps/_v-map-disclaimer.scss, app/assets/stylesheets/components/maps/_v-map-filters.scss, app/assets/stylesheets/helpers/_accessibility.scss, app/assets/stylesheets/helpers/_helpers.scss, app/controllers/country_controller.rb, app/controllers/region_controller.rb, app/javascript/components/map/VMap.vue, app/javascript/components/map/VMapDisclaimer.vue, app/javascript/components/map/VMapFilters.vue, app/javascript/components/map/default-options.js, app/javascript/components/map/helpers/request-helpers.js, app/javascript/components/map/mixins/mixin-bounding-box.js, app/javascript/components/map/mixins/mixin-layers.js, app/javascript/components/map/mixins/mixin-pa-popup.js, app/javascript/vue.js, app/views/country/show.html.erb, app/views/partials/maps/_header.html.erb, app/views/partials/stats/_stats-overview.html.erb, app/views/region/show.html.erb
Adds map to country and region pages.
Zooms to region/country on load - currently slow for regions.
e.g. /country/gbr or /region/europe
=> Map country and region

app/assets/stylesheets/components/_hero.scss, app/assets/stylesheets/components/hero/_hero-area-type.scss, app/assets/stylesheets/components/hero/_hero-basic.scss, app/assets/stylesheets/components/hero/_hero-home.scss, app/assets/stylesheets/components/hero/_hero-thematic.scss, app/views/home/index.html.erb, app/views/layouts/cms/_thematic-area-link.html.erb, app/views/layouts/partials/_hero-basic.html.erb, app/views/marine/index.html.erb, app/views/partials/carousels/_themes.html.erb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/129
=> Refresh icca

app/javascript/components/search/SearchSite.vue, app/javascript/components/search/SearchSiteInput.vue, lib/modules/search/aggregators/model.rb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/124
=> Make sure input it pre-populated on the site search results page

app/javascript/components/map/VMapFilters.vue, app/javascript/components/map/mixins/mixin-bounding-box.js, app/javascript/components/map/mixins/mixin-pa-popup.js, lib/modules/autocompletion.rb
Zooms and adds popup if PA (not working for region or country yet as the search doesn't)
=> add search pa zoom

app/javascript/components/search/SearchSiteInput.vue
=> Focus search site input on click

app/assets/images/icons/pin-outline.svg, app/assets/images/icons/pin.svg, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/base/mixins/_icons.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_tabs.scss, app/assets/stylesheets/components/maps/_v-map-popup.scss, app/assets/stylesheets/components/search/_search-results-areas.scss, app/controllers/search_areas_controller.rb, app/javascript/components/map/MapTrigger.vue, app/javascript/components/map/VMap.vue, app/javascript/components/map/default-options.js, app/javascript/components/map/mixins/mixin-pa-popup.js, app/javascript/components/search/SearchAreas.vue, app/views/home/index.html.erb, app/views/layouts/partials/_hero-thematic.html.erb, app/views/marine/index.html.erb, app/views/oecm/index.html.erb, app/views/partials/maps/_main.html.erb, app/views/partials/tabs/_tabs-thematic-area-database.html.erb, app/views/search_areas/index.html.erb, app/views/wdpa/index.html.erb, config/locales/search/en.yml
Add map to wdpa listing page (http://localhost:3000/en/search-areas?filters%5Bdb_type%5D%5B%5D=wdpa)
Style map trigger
Style popup on maps
=> Map search and popup

app/controllers/home_controller.rb, app/views/partials/cards/_circles.html.erb, config/locales/home/en.yml
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/12
Links have been added to the circular cards on the homepage that correctly route to Regions, Countries and Areas depending on the card being clicked.
=> made links on the home page route correctly to regions, areas etc.

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/components/_lists.scss, app/views/country/show.html.erb, app/views/partials/messages/_message-warning-stats.html.erb, config/locales/global/en.yml
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/127
=> Add files for malaysia country page

app/presenters/protected_area_presenter.rb, app/views/protected_areas/show.html.erb, config/locales/stats/en.yml
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/145
=> Fix broken management link and pull text out into yml file

lib/modules/autocompletion.rb
Adds designation name in brackets in autocomplete results for PAs with same name
=> Add designation name in autocomplete for PAs with same name

app/models/protected_area.rb
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/56)
=> Add wdpaid in the slug creation to make sure that is unique

app/presenters/protected_area_presenter.rb, app/views/partials/stats/_stats-affiliations.html.erb, config/locales/stats/en.yml
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/13
=> Put back work that was lost during merge conflicts

app/assets/stylesheets/components/_autocomplete.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/maps/_v-map-disclaimer.scss, app/assets/stylesheets/components/maps/_v-map-filter.scss, app/assets/stylesheets/components/select/_selector.scss
1,2,3 and 6 on this ticket: https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/148
=> map styling

app/controllers/search_controller.rb, app/helpers/cms_helper.rb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/161
=> Ticket 161

config/initializers/comfortable_mexican_sofa.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/168
Simple fix to get the CTA to export properly again.
=> fixed export of CTA

app/helpers/target_dashboard_helper.rb, app/views/target_dashboard/index.html.erb, config/locales/thematic_area/target_11_dashboard/en.yml
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/107
Replaced text in dashboard with Heather's suggestions
=> text replacements in dashboard

app/serializers/aichi11_target_dashboard_serializer.rb, app/serializers/aichi11_target_serializer.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/82
Changed connectivity bars (carousel and dashboard) to green.
=> Target 11 connectivity

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/base/_themes.scss, app/assets/stylesheets/components/_charts.scss, app/assets/stylesheets/components/_lists.scss, app/assets/stylesheets/components/charts/_am-chart-pie.scss, app/controllers/country_controller.rb, app/javascript/components/charts/am-chart-pie/AmChartPie.vue, app/javascript/vue.js, app/views/country/pdf/facts/_iucn_categories.html.erb, app/views/partials/stats/_stats-iucn-categories.html.erb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/171
=> Ticket 171

app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/components/search/_search-main.scss, app/assets/stylesheets/components/search/_search-results-areas.scss, app/javascript/components/search/SearchSite.vue
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/174
=> Ticket 174

app/controllers/search_controller.rb, app/javascript/components/search/SearchSite.vue, app/serializers/search/full_serializer.rb, app/views/search/index.html.erb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/125
=> Ticket 125

app/assets/stylesheets/components/_autocomplete.scss, app/javascript/components/download/Download.vue, app/views/layouts/partials/_footer.html.erb, app/views/layouts/partials/_topbar.html.erb, app/views/partials/global/_site-logo.html.erb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/180
=> Ticket 180

app/helpers/countries_helper.rb, app/views/partials/stats/_stats-iucn-categories.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/171
Populated the IUCN categories chart links with search results relating to the various categories for each country/region's PAs.
=> Ticket 171 links

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/cards/card/_card-stats.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-affiliations.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-attributes.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-management.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-overview.scss, app/assets/stylesheets/components/maps/_v-map-header.scss, app/assets/stylesheets/pages/_site.scss, app/assets/stylesheets/pdf.scss, app/views/country/show.html.erb, app/views/partials/stats/_stats-designations.html.erb, app/views/partials/stats/_stats-sources.html.erb, app/views/protected_areas/show.html.erb, config/initializers/assets.rb, lib/modules/comfy_opengraph.rb, lib/modules/download/generators/pdf.rb, package-lock.json, package.json, vendor/assets/javascripts/rasterize.js, yarn.lock
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/63
=> Ticket 33 pdf

app/controllers/home_controller.rb, lib/modules/stats/global.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/39
Added % PA coverage figure for homepage
=> populating coverage on homepage

app/controllers/protected_areas_controller.rb, app/views/partials/cards/_sites.html.erb
* Replace images lazy loader with a static loader to fix the wrong placeholder image
- Consider keeping lazy loading in the whole site
* Attempt to speed up queries by not selecting sites geometries
=> Ticket 185

app/assets/stylesheets/components/_lists.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-sources.scss, app/controllers/country_controller.rb, app/controllers/protected_areas_controller.rb, app/controllers/region_controller.rb, app/helpers/source_helper.rb, app/models/country.rb, app/models/protected_area.rb, app/models/region.rb, app/models/source.rb, app/views/partials/stats/_stats-sources.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/170
Added data for the sources table in the form: 
```
[ { title: ..., responsible_party: ..., year: ... } ... ]
```
Awaiting rework from Charlotte as the 'Details' link is no longer a link to a URL, but will be the party that created the source.
=> Sources table

lib/modules/sync_seeds.rb, lib/tasks/staging_seeds.rake
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/177
Wasn't just adjustments in the end, I ended up having to fix the `commence_import` method as it wasn't importing correctly (wrong source). Was probably a good idea that I left it commented out!
=> Sync seeds adjustments

app/helpers/cms_helper.rb, app/views/layouts/cms/_news-and-stories.html.erb, config/initializers/comfy_patching.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/187
Quick fix to remove Topics filters from News and Stories index page.
=> Remove types filter

app/models/region.rb, lib/modules/search/results.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/197
Remove global region from list of regions on search results page
=> remove global from list of regions on search results page

app/presenters/region_presenter.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/200
Fixed polygons-points count on region pages
=> fixed polygon and points count on region pages

lib/data/seeds/green_list_data.csv, lib/data/seeds/test_green_list_data.csv, lib/modules/wdpa/green_list_importer.rb
Added the new statistics from the September WDPA release 
Need to run `Wdpa::GreenListImporter.import_global_data` on staging to see the changes
=> added new green list data from september release

app/views/marine/index.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/210
Corrected the link in the button on the MPA page.
=> added correct link to view all marine sites

app/assets/stylesheets/components/_table.scss
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/204
Added a min height of the `filtered-table` component on tablet upwards so that the country filter modal doesn't get obscured by the footer.
=> Ticket 204

app/views/layouts/cms/_news-and-stories-article.html.erb, app/views/partials/social/_social-share.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/208
Added social sharing links to news pages as they were previously missing, and fixed the sharing links so they contain the URL of the current page to be shared.
=> Ticket 208

app/controllers/assets_controller.rb, app/helpers/application_helper.rb, app/javascript/components/search/SearchAreasResultsItems.vue, app/serializers/search/areas_serializer.rb, lib/modules/asset_generator.rb
* Add region and countries thumbnails in areas search
* Add delimiter to numbers in areas search
Not sure why Stanley's commit still appears even though I'm sure that has been pushed to refresh 🤷‍♂️ 
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/206)
=> Ticket 206

app/controllers/concerns/searchable.rb, lib/modules/search.rb
* Ensure full search also includes regions and countries
* Boost country index so that matched countries appear first
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/215)
=> Main search to include regions and countries

app/views/layouts/partials/_head.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/219
Added Hotjar tracking code to head
=> added hotjar tracking code

app/views/layouts/cms/_thematic-area-link.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/218
DB PR: https://github.com/unepwcmc/protectedplanet-db/pull/43
Updated ICCA page's layout partial with a call to render the content of the page
=> Ticket 218

app/assets/stylesheets/components/cards/card/_card-theme.scss, app/assets/stylesheets/components/cards/cards/_cards-facts.scss, app/views/partials/cards/_facts.html.erb, app/views/partials/sub_partials/_themes.html.erb, config/locales/home/en.yml, config/locales/map/en.yml
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/224
Assorted changes suggested by IUCN, on the homepage
=> Ticket 224

app/assets/stylesheets/components/_popup.scss, app/controllers/marine_controller.rb, app/helpers/downloads_helper.rb, app/javascript/components/download/DownloadPopup.vue
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/227
Added the MPA map to the dropdown list of downloads on the Marine Protected Areas page which will open in a new tab
=> added mpa map to marine protected areas page

app/javascript/components/charts/chart-column-tabbed/ChartColumnTabbed.vue, app/javascript/components/download/Download.vue, app/javascript/components/download/DownloadItem.vue, app/javascript/components/filters/FiltersSearch.vue, app/javascript/components/filters/vFilter.vue, app/javascript/components/form-fields/CheckboxSearch.vue, app/javascript/components/form-fields/Checkboxes.vue, app/javascript/components/form-fields/RadioButtonSearch.vue, app/javascript/components/forms/DownloadCsv.vue, app/javascript/components/listing/ListingPage.vue, app/javascript/components/pame/DataFilter.vue, app/javascript/components/search/SearchAreas.vue, app/javascript/components/search/SearchSite.vue, app/javascript/components/tabs/Tabs.vue, app/javascript/components/tabs/TabsFake.vue, app/javascript/vue.js, app/views/green_list/index.html.erb, app/views/layouts/cms/_equity.html.erb, app/views/layouts/cms/_news-and-stories.html.erb, app/views/layouts/cms/_resources.html.erb, app/views/marine/index.html.erb, app/views/oecm/index.html.erb, app/views/pame/index.html.erb, app/views/partials/charts/_chart-top-ten.html.erb, app/views/partials/download/_download.html.erb, app/views/partials/tabs/_tabs-equity.html.erb, app/views/partials/tabs/_tabs-thematic-area-database.html.erb, app/views/search/index.html.erb, app/views/search_areas/index.html.erb, app/views/wdpa/index.html.erb
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/61
=> Event tracking

app/javascript/components/counter/Counter.vue
Make sure Green list coverage % matches up on the page.
=> Make sure counter rounds correctly

app/controllers/protected_areas_controller.rb
Site page - Other sites not showing correctly yet. Site with WDPA ID 555547601 only shows 2 more sites (the given site is the only site in the country).
=> Ensure to pull the correct number of other sites

app/helpers/equity_helper.rb
=> link on equity component is now functional

app/helpers/search_helper.rb, app/views/partials/stats/_stats-designations.html.erb, lib/modules/search/templates/aggregations.json
Add designation link to search page
=> Add designation link to search page

app/assets/stylesheets/components/_nav.scss, app/assets/stylesheets/components/charts/_chart-legend.scss, app/assets/stylesheets/components/charts/_chart-row-pa.scss, app/assets/stylesheets/components/select/_select-equity.scss, app/controllers/green_list_controller.rb, app/helpers/green_list_helper.rb, app/helpers/marine_helper.rb, app/views/green_list/index.html.erb, app/views/marine/index.html.erb, app/views/partials/charts/_chart-row-pa.html.erb, config/locales/thematic_area/green_list/en.yml, config/locales/thematic_area/marine/en.yml
+ changes to equity that weren't pushed before
+ update chart on the green list page to use tooltips for both bars
+ make sure nav scrolls on mobile
=> Make sure nav scrolls on mobile

app/controllers/concerns/tabs.rb, app/controllers/oecm_controller.rb, app/controllers/pame_controller.rb, app/controllers/wdpa_controller.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/162
=> Make sure 4th tab on PAME shows up on the frontend.

app/controllers/application_controller.rb, app/controllers/protected_areas_controller.rb, app/views/layouts/500.html.erb, config/locales/global/en.yml
* Add quick 500 page (same for 404 page) rescuing from standard error
* Improve location filter in PA show page
=> Add 500 page

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/cards/card/stats/_card-stats-overview.scss, app/assets/stylesheets/helpers/mixins/_icons.scss, app/models/protected_area.rb, app/presenters/protected_area_presenter.rb, app/views/partials/stats/_stats-overview.html.erb, config/locales/stats/en.yml, config/secrets.yml
* Add World Heritage Outlook link to PA page if PA is designated as a World Heritage Site
* Increase map size in PA page only, so it matches the height of the stats section on the left (especially if there are many links)
@stacytalbot I've added a TODO comment with regards the `button_title` text in the locales YAML. That doesn't seem to be used so it would be good to double check what we should do with that.
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/138)
=> Add who link

app/workers/import_workers/finaliser_worker.rb, lib/modules/active_storage_transfer.rb, lib/modules/wdpa/protected_area_importer/attribute_importer.rb
Ensure to also transfer the ActiveStorage related tables so to not lose reference to attachments (e.g. background images)
⚠️ Please test this properly before merging
=> Active storage transfer

app/javascript/components/download/DownloadItem.vue, app/views/layouts/partials/_head.html.erb, app/workers/download_workers/search.rb, config/secrets.yml, lib/modules/download/poller.rb, lib/modules/download/queries.rb, lib/modules/download/requesters/base.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/171
Fix for tasks 1 and 4 of the ticket. Tasks 2 and 3 will need a 'proper plan' according to Heather.
=> Fix/ticket 171 (tasks 1 and 4)

app/controllers/application_controller.rb, app/javascript/components/tabs/Tabs.vue, app/views/pame/index.html.erb, app/views/partials/tabs/_tabs-thematic-area-database.html.erb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/183
Set up pages with tabs on them (Thematic Area pages) so that they now add a `tab` param to the URL query string when accessed which enables specific tabs to be directly linked to.
=> Link to tabs

app/controllers/assets_controller.rb, config/secrets.yml, lib/modules/asset_generator.rb
Fix up map thumbnails.
Issue was mainly due to us using an old classic style.
Not an obvious way to deal with the logo at this stage so leaving for now as it is more important to get the tiles up on prod.
N.B - New var needed for .env file
=> Map thumbnails

Gemfile.lock
Requesting to merge changes to Gemfile.lock into develop now that `bundle update mimemagic` has been run.
=> Fix mimemagic versioning error

app/helpers/equity_helper.rb, app/javascript/components/select/SelectEquity.vue
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/214
Equity page dropdown component will now render link to the associated PA page for each area in the dropdown only if the PA exists in the DB
=> Conditionally render link to PA page if WDPA ID found

config/locales/map/en.yml
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/173)
=> Add missing text to map disclaimer

app/controllers/global_statistics_controller.rb, app/models/global_statistic.rb, app/views/home/index.html.erb, config/routes.rb, lib/modules/wdpa/global_stats_importer.rb
Adds a download link for the global statistics csv
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/261
Testing:
go to the home page, click the download link
=> feat: added a download link for global statistics

app/controllers/pame_controller.rb, app/models/pame_evaluation.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/268
Uses the last PAME data file to set downloaded file name instead of a constant
=> feat: Use latest PAME data csv for date of generated download csv

app/views/home/index.html.erb
Moved download link adjacent to latest file info as requested by Charlotte
http://localhost:3000/en
=> feat: moved download link to same line as latest update

app/assets/stylesheets/helpers/_cms.scss
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/249
Adds a table border to CMS resource content.
Testing:
http://localhost:3000/en/resources/september-2020-update-of-the-wdpa
=> fix: add table borders to resources pages

app/controllers/green_list_controller.rb, app/controllers/marine_controller.rb, app/controllers/oecm_controller.rb, app/controllers/wdpa_controller.rb, app/helpers/map_helper.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/286
=> fix: pass the correct point query urls to each map component

config/locales/home/en.yml
[289](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/289)
- Change home page heading (this has to be done manually from the cms interface)
- Change home page button text
=> Change Home page heading & button text

app/views/marine/index.html.erb, config/locales/thematic_area/marine/en.yml
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/152
=> fix: move cms content to locale for updated statictics

docker-compose.yml, docs/docker.md
I added this to the .env file in protectedplanet-api to get it to work
```
APPSIGNAL_LOG_PATH=/var/log/appsignal/protectedplanet-api.log
```
=> feat: add api as a service in docker-compose.yml

config/locales/home/en.yml
Testing:
start app, look at button at top of home page. it should look like this, but with less capital letters
=> feat: make 'protected areas' lowercase in button text

.env-jenkins-docker, Jenkinsfile
…CK in env and also added API_PATH
=> Fix/dockercmd-jenkins: ensure yarn install works by assigning some value to SSH_AUTH_SOCK in env and also added API_PATH

app/javascript/components/charts/chart-column-tabbed/ChartColumn.vue, app/presenters/region_presenter.rb
| Type | Description |
| - | - |
| Fix | Percentage that are over 100 should be capped at 100% for Marine Protected Areas  |
See [Staging site](https://pp.new-web.pp-staging.linode.protectedplanet.net/en/thematic-areas/marine-protected-areas) for the fix
**Design:**
**Codebase:** 
[#173](https://unep-wcmc.codebasehq.com/projects/data-infrastructure-refactor/tickets/173)
**Resources**
=> Fix percentage over hundard

lib/data/seeds/global_statistics_2024-07-01.csv
fix the issue with the header Value (first letter uppercase rather than lowercase) in Global Statistics CSV for monthly release
=> chore: fix the issue with the header "Value" in Global Statistics CSV

lib/modules/asset_generator.rb
- We have now set whitelist only to allow pp server/urls to use the mapbox token
- referer header added to the request
[ticket](https://planner.cloud.microsoft/webui/v1/plan/kVmgrGNdBEaKkS4e3k3fA5cAGGmX/view/board/task/pj5z0ifdZE6DtW1O0iLTJZcAINo6?tid=2faab858-d1f4-48af-86f6-486196d5969d)
- The production server mapbox token env will need to be updated to use the new token after this PR is merged
=> fix: add referer so Mapbox knows the request comes from pp server
