unepwcmc/ProtectedPlanet

app/models/protected_area.rb
This adds the number of networks and the number of designations to the protected areas api.
=> Add networks number and designations number to PAs API

app/assets/javascripts/modules/protected_areas/base.js.coffee, app/assets/javascripts/modules/protected_areas/overlap.js.coffee, app/assets/javascripts/protected_areas.js, app/controllers/api/v3/protected_areas_controller.rb, app/models/protected_area.rb, app/views/protected_areas/_pa_card.html.erb, config/routes.rb
Use AJAX to retrieve overlap calculations between PAs.
This helps to load the page quicker and wait for the calculation to be done before populating the PA cards.
I think a spinner would be nice to add for each PA card while waiting for those value.
=> Fix percentage overlap

app/views/region/facts/_coverage_stats.html.erb
- Fixed to zero decimal places when showing the kilometers squared.
- Fixed to two decimal places for percentages.
=> Fixed percentage decimal places

app/assets/stylesheets/custom.scss, app/presenters/region_presenter.rb, app/views/cms/_countries_by_regions.html.erb
Added links to the regions page from unep-regions page and fixed two issues which appeared on staging;
- The `region.js` was not being precompiled so I had to add that to the config.assets.precompile in application.rb,
-  A minor adjustment to add `regional` to the `sources_per_jurisdiction_hash` to fix bug.
=> Add links to regions pages from unep regions page

CHANGELOG.md, app/views/search/_protected_area.html.erb
* Use WDPA ID instead of slug for the show pages to prevent issue with protected areas with same name
=> Release 2.1.5

app/helpers/cms_helper.rb, app/presenters/cms_presenter.rb, app/views/cms/_children_nav.html.erb, app/views/cms/_siblings_nav.html.erb, app/views/cms/blog/_index.html.erb, app/views/marine/sections/_coverage_map.html.erb
- Make sure that all blog posts are listed in on the Blog page (not just the direct children of the Blog page) - this returns an array of hashes instead of a hash
- Fix up year/month filter to work with an array of hashes
- Fix up the sibling and child templates so that they only show published pages
- Make year on the marine page dynamic
=> Fix blog results

lib/modules/search/index.rb, test/integration/search_page_test.rb, test/integration/search_test.rb, test/unit/search/index_test.rb
the static methods now act on both indexes and don't take an
index_name as an argument. The object methods act on a single index
and the index_name is assigned on construction. new and create are
separated out so the flow goes new -> create -> index and then its
ready for search, then can cleanup with delete
=> Rationalised the index interface

Dockerfile
This is the initial work to add phantomjs via the newly updated `unepwcmc-geospatial-base` docker image. 
You can find phantomjs at `/usr/bin/phantomjs`
Please remember to run `docker-compose build` before `docker-compose up` to see this change. It will take a few minutes to rebuild.
=> Use latest unepwcmc-geospatial-base image with phantomjs support

app/models/pame_statistic.rb, lib/modules/stats/global.rb
A small fix to include ABNJ (Area Beyond National Jurisdiction) and ATA (Antarctica) in the global stats calculations.
Statistics objects with `nil` country_id are referring to those particular areas.
Also make sure to calculate global Pame stats correctly.
=> T11 adjust global stats

app/controllers/target_dashboard_controller.rb, app/models/aichi11_target.rb, app/serializers/aichi11_target_serializer.rb, lib/modules/stats/country_statistics_api.rb
This saves stats fetched from the API into the Aichi11Target table related to:
* importance
* well connected
* representative
This also results in a faster initial page load.
⚠️ `bundle exec rake db:migrate` required from [this branch]/PR(https://github.com/unepwcmc/protectedplanet-db/pull/22)
⚠️ Please read notes on that db PR as well.
Related ticket: [Initial page load - Global stats](https://unep-wcmc.codebasehq.com/projects/pp-target-11-dashboard/tickets/39)
=> T11 save global stats

Gemfile, Gemfile.lock, config/deploy/production.rb, config/sidekiq-import.yml, config/sidekiq.yml, lib/modules/countries_geometry_importer.rb, lib/modules/s3.rb, lib/modules/wdpa/s3.rb, test/unit/wdpa/s3_test.rb
This is to fix the WDPA import process after the overall upgrade of the code.
I have tested this on the new production server only and seems working fine but please double check if you notice something odd http://pp.new-web.pp-production.linode.protectedplanet.net/
:warning:  Be aware that this includes the branch `new_production_deploy` where the gem activerecord-postgis-adapter has been updated to fix the issue with the search by country.
Furthermore, the capistrano deploy files point to the new server (staging and production).
=> Fix wdpa import  after upgrade aws-sdk gem from v1

app/helpers/target_dashboard_helper.rb, app/serializers/aichi11_target_dashboard_serializer.rb
## Description
Fix sorting not working for coverage and effectively managed.
This was happening because the wrong key was being passed to the hash of each record to fetch the values.
=> Fix sorting for coverage and effectively_managed

app/models/country.rb, lib/modules/stats/country_statistics_importer.rb
Changes necessary for having `assessments` and `assessed_pas` populated within the PameStatistic model.
These changes are useful for [this API PR](https://github.com/unepwcmc/protectedplanet-api/pull/15) while we follow up on having those figures within the provided CSV file.
To test this locally and on staging you need to perform the following in the rails console:
```
> ImportTools.statistics_monthly_import
```
=> Import assessments in PameStatistic

app/presenters/region_presenter.rb
## Description
Fix coverage percentage calculations for regions.
The percentage should be calculated based on the sum of the total protected area and the sum of total area (for both land and marine)
=> Fix coverage percentage stats

lib/modules/wdpa/pame_importer.rb
## Description
Add country association regardless of wdpaid being present.
[Ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/116)
`Wdpa::PameImporter.import` and then `ImportTools.statistics_monthly_import` are required to apply the fix to the db.
=> Fix countries assessments count mismatch

lib/modules/download/generators/shapefile.rb, test/unit/download/generators/shapefile_test.rb
It has been reported that the shapefile download generates a unique large shapefile which is diffcult or impossible to work with (probably due to the 2GB limitation for shapefiles).
This PR has got some adjustments that would split the data into 2 shapefiles by default, but more generally allows to specify the number of shapefiles desired when exporting.
Needs to be tested on staging properly.
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/112)
=> Allow to split data into multiple shapefiles

app/assets/images/icons/minus.svg, app/assets/images/icons/plus.svg, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/maps/_v-map-baselayer-controls.scss, app/assets/stylesheets/components/maps/_v-map-filters.scss, app/javascript/components/map/default-options.js, app/javascript/components/map/mixins/mixin-controls.js, app/views/home/index.html.erb, app/views/partials/maps/_main.html.erb
- Add zoom styling
- Use `$small` for tablet breakpoint
- Change some of the measurements to match xd designs
- Add dark grey (inverse) selected state to baselayer toggles (as advised by Charlotte) and adapt existing active/hover styles to suit
- Keep focus outline (for accessibility)
- Move attribution to bottom left (compact version on mobile needs fixing at a later date)
- Add padding to edge of map for tablet+
=> add zoom styles and edit control styles to match px in designs

Gemfile.lock
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/100
I rolled back `comfy_bootstrap_form` version to 4.0.7 to allow checkboxes in the CMS to be selected once more. It seems to be related to incorrect inputs present in the form inside the Comfy gem.
=> Checkbox bug fix

app/controllers/country_controller.rb, app/controllers/region_controller.rb, app/controllers/search_controller.rb, app/helpers/map_helper.rb, app/models/country.rb, app/models/region.rb, app/views/partials/maps/_main.html.erb, config/locales/main_map/en.yml, lib/modules/autocompletion.rb
This adds extent_url method to country and region models.
Also only adds oecm filter to search if 'oecm' or 'wdpa' is the db_type. Otherwise filters = {}
You can test this on the map search on the homepage.
BUG: I can't get OECMs to be found either if I set db_type = oecm or db_type = site (therefore filters = {})...
=> Location search

Gemfile, Gemfile.lock, app/models/pame_evaluation.rb, lib/modules/wdpa/pame_importer.rb
## Description
* Restore original Pame importer as it wasn't importing the `wdpa_id` field correctly, resulting in some issues also with the download (e.g. showing 0 for that field and having the same evaluation downloaded multiple times because wouldn't be able to match fields using the UNION statement; which statement has also be removed by the way)
* Remove UNION statement for downloading hidden evaluations (where protected_area_id is empty) so that the CSV matches exactly what it shown on the table.
## Notes
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/150)
=> Ticket 150

config/initializers/comfy_patching.rb
To test, try deleting pages with the custom tags added and it should successfully delete.
=> added dependent destroy on pages categories to allow deletion

app/helpers/cms_helper.rb, app/serializers/search/cms_serializer.rb, app/views/layouts/cms/_resource.html.erb, app/views/partials/cards/_articles.html.erb, config/initializers/comfy_patching.rb
Bug fix for staging, to allow the custom tag `date_not_null` to be properly sorted in the views as the Comfy helper `cms_fragment_content` is not properly configured to work with it (returns its content which is nil).
=> Allow custom datetime tag to work

app/helpers/cms_helper.rb
Fix 500 error when clicking on resources pages.
The error seems related to missing attachments still. Cleaning up the staging db more might help as well.
Here I'm returning an empty string instead if attachments are missing, which should be more future proof.
=> Return empty string if attachment is missing

config/initializers/comfy_patching.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/190
Added `date_not_null` to the monkey patch, so that it uses `datetime` instead of `content`, which means that it should export its datetime to the `content.html` that it generates for each page.
=> export date not null's datetime as content

app/javascript/components/map/default-options.js, app/javascript/components/map/mixins/mixin-add-layers.js
This hopefully will work - I couldn't test locally. It uses the old tilesets (which are added into a style). This does mean that the basemap is no longer a series of layers, meaning polygons will have to be added on top of the place names and boundaries, rather than beneath them.
=> use old pp maps

app/models/protected_area.rb, app/presenters/protected_area_presenter.rb, lib/modules/download/queries.rb, lib/modules/wdpa/data_standard.rb
Amend model and importer to account for the new OECM attributes stored in the ProtectedAreas table
Related [DB PR](https://github.com/unepwcmc/protectedplanet-db/pull/41)
=> Ensure OECM attributes can be set only if PA is an OECM area

app/models/country.rb, app/models/protected_area.rb, app/models/region.rb, lib/modules/download/queries.rb, lib/modules/wdpa/data_standard/source.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/203
PR for migration: https://github.com/unepwcmc/protectedplanet-db/pull/42
I've added `update_year` (corresponding to the `update_yr` column in the standard_sources table of the WDPA) to the sources data standard module, as well as correcting the class methods responsible for populating the sources tables so that they now use the correct attribute. 
@Levia Please let me know if this is all that is needed - I've checked myself and the Source model seems well isolated from the rest of the database. 
We'll need to re-import the WDPA on staging, or just the sources if it's possible to do so to see the changes.
=> Ticket 203

app/presenters/home_presenter.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/205
Changed 'OECMs' on homepage's fact card component to read 'Protected Areas'
=> corrected OECMs on homepage fact cards to protected areas

app/controllers/green_list_controller.rb, app/models/protected_area.rb, app/presenters/region_presenter.rb, lib/data/seeds/green_list_sites.csv
Candidate GL sites are now excluded from the GL coverage growth chart, so only GL and relisted sites are present, also there is a small fix for the 'top 10 per region' chart because a line in the method used to build the chart was erroring as there were more than 10 countries with GL sites in a particular region. That chart actually has fixes for it in another branch/PR, I didn't want to clutter this one.
=> Exclude gl candidates

app/controllers/protected_areas_controller.rb
Redirect to search page if PA is found by slug or render show page as usual if found by WDPA ID.
Raise 404 if PA is not found at all.
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/217)
=> Redirect to search page if PA found by slug

config/initializers/comfy_patching.rb, lib/tasks/cms_categories.rake
Fix issues related to CMS custom categories:
* Ensure categories related tables have been created before doing anything in the `after_save` method.
* Ensure categories data exist as soon as tables are created so that CMS seeds import works fine too. (See [related DB PR](https://github.com/unepwcmc/protectedplanet-db/pull/44) for this)
[Related DB PR](https://github.com/unepwcmc/protectedplanet-db/pull/44)
[Codebase Ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/221)
=> Ticket 221

app/views/partials/stats/_stats-related-countries.html.erb
Remove redundant header for related countries and territories sections as described in the [codebase ticket](https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/211)
=> Remove redundant header for related countries and territories

Gemfile, Gemfile.lock
This was mainly to add what was the only thing left in the refresh-copy branch that wasn't on refresh yet.
Added the net-scp gem which turned out to be necessary when running the staging CMS import task
=> Add net-scp gem for the staging importer task

app/controllers/oecm_controller.rb, app/views/oecm/index.html.erb, app/views/partials/maps/_main.html.erb, app/views/partials/tabs/_tabs-thematic-area-database.html.erb
This should centre the map on roughy mexico on the oecm page. Other maps should be unaffected. 
Worth checking the oecm, wdpa, marine and home pages to check there are no issues with undefined local variables etc.
=> adjust initial center location for oecm map

app/models/pame_evaluation.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/164
Added Type filter to PAME page to allow filtering by either Marine or Terrestrial areas. Filtering carries over to CSV download 
Need to check that Marine filter incorporates coastal areas as well.
=> Ticket 164

app/assets/stylesheets/components/cards/card/_card-theme.scss, app/presenters/thematic_areas_presenter.rb, app/views/partials/sub_partials/_themes.html.erb
- Ribbon with number of sites has been reinserted in the top left of the applicable thematic carousel cards. 
- Text now positioned directly below it and at the same height for all cards regardless of whether a ribbon is present or not. 
- Carousel height has also been increased to allow summary text to show if a particular card has too much text (see the ICCA one).
=> Reinsertion of ribbon

app/controllers/search_controller.rb, app/javascript/components/map/VMapPASearch.vue, lib/modules/autocompletion.rb, lib/modules/search.rb
This fixes the autocomplete in maps search and other pages search (e.g. WDPA, OECM, home page).
Honestly it's not the solution I was looking for, but after spending some time trying to tweak elasticsearch and failing, this was probably the quickest solution.
I've added a comment about this to remember and research other solution (probably separating the indexes or similar)
=> Tweak autocomplete to also fetch countres and regions correctly

public/robots.txt
Fix for problem where Googlebot indexes PDF files but closes the connection before the PDF file has been generated.  
66.249.79.241 - - [07/Oct/2020:09:25:30 +0100] "GET /555610076.pdf HTTP/1.1" 499 0 "-" "Googlebot/2.1 (+http://www.google.com/bot.html)"
66.249.79.243 - - [07/Oct/2020:09:30:50 +0100] "GET /555518707.pdf HTTP/1.1" 499 0 "-" "Googlebot/2.1 (+http://www.google.com/bot.html)"
"last_data_send_time" : null,
"method" : "GET",
"next_request_early_read_error" : "The client connection is closed before the request is done processing (errno=-1020)",
"path" : "/160904.pdf",
"refcount" : 1,
"request_body_already_read" : 0,
"request_body_fully_read" : true,
"request_body_type" : "NO_BODY",
"response_begun" : false,
"session" : {
"gupid" : "1976c9a-N6BKVgxQKF",
"pid" : 18586
}, …
=> Fix to stop Googlebot from indexing PDF files

app/controllers/application_controller.rb, config/locales/meta/en.yml, lib/modules/comfy_opengraph.rb, lib/modules/s3.rb
~~Set the Twitter card to use 'summary_large_image' and also use 4096 x 4096 (the maximum size) variants in case images are too large for Twitter~~
EDIT: After setting the staging S3 bucket to public-read, setting the Content-Type of the images and resizing the images, the S3 hosted hero images still cannot be loaded by the web crawlers used by the social media bots. I've resorted to using the default social image for all pages which can be shared - which as it turns out still doesn't work on the news pages for unknown reasons (the GL page and other thematic area pages work). There are still useful changes I've made so this should still be merged in. 
Also, apologies for the messy commit history, tried to amend commits after pushing (instead of before)
=> social media previews

Capfile, config/deploy.rb, config/deploy/staging.rb
This is designed to better handle sidekiq processes.  For it to work 2 systemd scripts will need to be installed on the server.  
These can then be run standalone by
sudo systemctl start pp_import.service
sudo systemctl stop pp_import.service
sudo systemctl restart pp_import.service
sudo systemctl start pp_default.service
sudo systemctl stop pp_default.service
sudo systemctl restart pp_default.service
These will also be restarted at the end of the deploy so that they should always point to the current folder
Currently monitoring is handled by nagios, but when we upgrade to sidekiq 6 this should automatically be handled by systemd watchdog service
=> Sidekiq fix

app/controllers/protected_areas_controller.rb
Sites can have no countries attached apparently.
This means that the view all button should redirect to search page with all areas instead of throwing an exception.
Also, the 'view all' button was not taking into consideration the country correctly as well. This has also been fixed.
## Notes
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/159)
=> Fix site with no country

lib/modules/search/index.rb, lib/tasks/search.rake
Add rake task to reindex only the CMS.
This is useful so that the scheduled job that runs every night only reindexes the CMS instead of the whole thing.
The CMS is the only thing that could change potentially every day.
The idea is that after this is merged we can change the scheduled job to run:
``` bundle exec rake search:cms:reindex```
instead of:
``` bundle exec rake search:reindex```
=> Add rake task to reindex only the CMS

app/controllers/marine_controller.rb, app/presenters/home_presenter.rb
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/176
Statistics are now aligned on the homepage cards and the MPA page. The MPA page now no longer takes OECMs into account in the statistics, just PAs. Likewise, the number of marine protected areas on the homepage (excluding OECMs) now uses `GlobalStatistic` to populate it, as opposed to performing a query on the ProtectedArea model.
=> stats now aligned on homepage and mpa page

config/deploy.rb, lib/tasks/cache.rake
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/185
This should hopefully solve all the issues regarding missing content on pages that often occurs after a deploy. Turns out that there was already an old Rake task for clearing the Rails cache, all I've done is add it as a callback to the deploy:publishing hook. 
I've checked and `Rails.cache.clear` does not clear the Redis cache, either directly through the console, checking both the Redis keys and manually through checking the downloads on the website itself before, during and after clearing the cache. I'm not 100% sure, but I think this means that the downloads are safe and shouldn't be reset.
=> fix/invoke rails:cache:clear post-deploy:finishing

app/controllers/pame_controller.rb, app/javascript/components/forms/DownloadCsv.vue, lib/modules/download/generators/base.rb, lib/modules/download/generators/gdb.rb, lib/modules/download/generators/shapefile.rb, lib/modules/download/utils.rb, lib/modules/ogr/command_templates/postgres_gdb_export.erb, lib/modules/ogr/postgres.rb, lib/modules/wdpa/s3.rb
* PAME download filename to follow YYYY-MMM version convention
* Standardise downloads filenames and features layers within GDB.
* For GDB exports, include source table within GDB file itself as in the original monthly release GDB
~~## TODO~~
~~* Single site downloads filenames should have a suffix to identify the area downloaded~~
~~* Look into splitting shapefiles into 3 parts only when strictly necessary (e.g. currently 3 shapefiles are generated even when downloading a single site)~~
[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/188)
=> Ticket 188 downloads name

Gemfile, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, lib/capistrano/tasks/cache.rake, lib/tasks/cache.rake
This is a second, more formal attempt to allow the rake task to clear the cache to run during deployment.
A new Capistrano task has been created in `lib/capistrano/tasks` to allow the Rake task it calls access to the current environment, either staging or production. This should no longer therefore error during deployment. 
Also, the byebug gem has now been added to staging as well for better debugging. 
I'd recommend first to try to deploy to staging before merging in.
=> Clear cache

app/assets/stylesheets/components/_hero.scss
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/198 
Added `display: none` to the `hero-stat-bubble` mixin along with a comment to indicate that it's temporarily hidden.
=> refactor: temporarily hide circular stats div on wdpa, oecm and homepage

lib/data/seeds/jurisdictions.csv
**Ticket**
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/122
- Include 'Not Applicable' in `jurisdictions.csv` in the `seeds` folder. This fixes the reported issue of PAs being returned with `nil` jurisdiction. On production I'll manually create the new Jurisdiction before running the import again. 
Other changes in the ticket will be made in a separate PR
**Notes**
Seeding a new db will automatically create the missing jurisdiction. 
In an existing db, can only really be tested by creating a new Jurisdiction instance with 'Not Applicable' as the name and then importing the monthly release into that DB.
=> Fix the API

lib/modules/download/utils.rb
Codebase ticket  https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/218
When the full dataset gets downloaded from the search page https://pp.new-web.pp-staging.linode.protectedplanet.net/en/search-areas?geo_type=country without applying any filters or search term, an identifier (SHA256 hash) gets unnecessarily added as a suffix to the filename.
This is a hotfix to prevent this
=> Ticket 218/filepath too long

app/javascript/vue.js, app/views/layouts/application.html.erb, app/views/layouts/partials/_cookieconsent.html.erb, package-lock.json, package.json, yarn.lock
**This Pull Request addresses Protected Planet - Support & Maintenance [Ticket 163](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/163), "Cookie Compliance Banner".**
I tried to use the `cookieconsent` gem at first, but came across some problems where Sprockets wasn't including it, so I went via the npm/webpacker route instead.
- `cookieconsent` package added via npm and imported in `vue.js`
- `_cookieconsent.html.erb` partial created to store the necessary script tag where the cookieconsent banner is initialised.
- That partial is then rendered at the top of the body in `application.html.erb`.
Note: There are lots of config options to customise the appearance and behaviour of the banner. I've left it quite simple for now and given the button a …
=> Add cookie banner using cookieconsent package

app/assets/stylesheets/components/_download.scss, app/javascript/components/download/Download.vue, app/views/country/show.html.erb, app/views/partials/bars/_topbar-secondary.html.erb, app/views/partials/download/_download.html.erb
These changes address [Ticket #211](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/211).
The aim of these changes was to disable the "Download" button in the topbar of the Country#show view if the country has no WDPAs, e.g. for the Vatican City (see screenshot).
@stacytalbot suggested that the disabled button have similar styles to the disabled "Filter" button on the country search view (see screenshot).
=> Country#show: Disable download if no wdpas

app/assets/stylesheets/base/_buttons.scss, app/assets/stylesheets/components/modal/_modal-download-commercial.scss, app/assets/stylesheets/utilities/_media-queries.scss, app/helpers/downloads_helper.rb, app/javascript/components/download/DownloadCommercial.vue, config/locales/download/en.yml
Update the text on the download popup.
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/175
Used purple button instead of green to keep consistent with the style guide.
Example url: https://www.protectedplanet.net/en/search-areas?geo_type=region
Click on Download then CSV to open the modal
=> T175 commercial

app/controllers/marine_controller.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/256
Removed the MP button download.
Testing:
'MPA Map' should no longer appear in the download list on https://www.protectedplanet.net/en/thematic-areas/marine-protected-areas
=> feat: hide mpa button download and left comment

app/javascript/components/pages/RegionCountryPages.vue
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/265
Hides the growth chart on country and region show pages, because they aren't calculated correctly or showing area. 
Testing:
go to a country page, e.g., http://localhost:3000/country/JOR
see no growth chart
=> feat: hid PA growth chart from country and region pages

app/serializers/search/base_serializer.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/273
Regions returned by filter results did not link correctly to the region page
Testing:
search for a region (north america, europe, africa etc)
link should take you to that page
NOTE: bounding box isn't selected properly. think this should be fixed in another ticket where will try to pass up bounding boxed using our own database, because the bounding boxes from the api we use has issues (e.g. dateline bounding boxes fail)
=> fix: give correct link for regions in filter results

app/helpers/map_helper.rb, app/models/protected_area.rb
https://unep-wcmc.codebasehq.com/projects/gef-spatial/tickets/1
Some api requests are broken after recent API changes. they work again if we submit a number instead of a string
=> fix/Changed urls so they work after recent API changes

CHANGELOG.md, app/helpers/map_helper.rb
fixes broken country url
got to home page, enter country into search on map
should zoom to country
same for region, e.g. Latin America & Caribbean
=> fix: country zoom url

lib/modules/wdpa/release.rb, lib/modules/wdpa/s3.rb, test/unit/wdpa/release_test.rb, test/unit/wdpa/s3_test.rb
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/272
Second attempt at fixing this bug.
File downloads always point at the latest version of the database in the s3 buckets. Last attempt to fix it broke because the monthly import looks in the same place as the file downloads for the file, so it was only finding the current release's file using the constants in the constants.rb, not the newer one.
This points file downloads to the current release files and the monthly import to the current release. 
Testing:
I found it easiest to update the secrets file so all development credentials point to the production buckets, then:
download a csv and shapefile for a country (jordan and Tanzania had changes recently so is a good choice)- should be the latest …
=> Use correct bucket for file downloads

app/javascript/components/stats/StatsCoverage.vue
https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/288
testing:
go to country or region show pages and look at the square coverage diagrams. 
LUX has highest `http://localhost:3000/country/LUX`
=> fix: calculate the edge length of squares in the coverage diagrams

app/models/region.rb
PAs shared between two countries within the same region are counted twice in the regional statistics
e.g. https://www.protectedplanet.net/region/na
number of PAs 52727
number of unique PAs 52725
=> fix: pa count

app/models/region.rb
PAs shared between two countries within the same region are counted twice in the regional statistics
e.g. https://www.protectedplanet.net/region/na
number of PAs 52727
number of unique PAs 52725
=> fix: PA count on regional page

app/assets/stylesheets/components/maps/_v-map-disclaimer.scss, config/locales/map/en.yml
This PR update the text for the disclaimer on the map. To test it, run the app and the new disclaimer should show:
```
The designations employed and the presentation of material on this map do not imply the expression of any opinion whatsoever on the part of the Secretariat of the UnitedNations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries.
- Dotted line represents approximately the Line of Control in Jammu and Kashmir agreed upon by India and Pakistan. The final status of Jammu and Kashmir has not yet been agreed upon by the parties.
- Final boundary between the Republic of Sudan and the Republic of South Sudan has not yet been determined.
- Final status of the Abyei area is not yet …
```
=> fix: update disclaimer text

CHANGELOG.md, app/models/concerns/geometry_concern.rb, lib/modules/asset_generator.rb
needs to go to master because develop has new features on it.
Restores previous method of generating mapbox thumbnails. will fail on very large geojsons, as before.
Testing:
go to http://localhost:3000/en/search-areas?filters%5Bdb_type%5D%5B%5D=wdpa
thumbnails should load as you scroll down the page
=> fix: revert mapbox geojson simplification methods

lib/modules/wdpa/data_standard.rb
https://unep-wcmc.codebasehq.com/projects/data-infrastructure-refactor/tickets/185
https://unep-wcmc.codebasehq.com/projects/data-infrastructure-refactor/tickets/188
Linked API PR: https://github.com/unepwcmc/protectedplanet-db/pull/54
Modifies the importer so it imports the additional fields from the WDPA release.
:verif and :parent_iso are imported as is
:marine is imported to :marine_type, which is then used to calculate the existing :marine attribute
=> feat: add new atributes for api via the importer

app/controllers/country_controller.rb, app/models/country.rb, app/models/pame_evaluation.rb, lib/modules/wdpa/pame_importer.rb
https://unep-wcmc.codebasehq.com/projects/data-infrastructure-refactor/tickets/196
[notes for context](https://github.com/unepwcmc/ProtectedPlanet/wiki/PAME-Evaluation-Notes)
PAME Evaluations for a given country are shown in different places:
- [Country page](https://www.protectedplanet.net/country/FRA)
- [PAME table](https://www.protectedplanet.net/en/thematic-areas/protected-areas-management-effectiveness-pame?tab=Results)
- API (pame_statistic.assessments)
1. Run `ImportTools.statistics_monthly_import` 
2. Check that transboundary sites are excluded from the count if only the other country has PAME evaluation assigned (e.g. POL-BLR, wdpa_id: 2008)
3. Check that PAME table doesn't include overseas territories (e.g FRA)
4. Check that regional statistics are unchanged
=> Make PAME stats consistent within PP and PP API

app/controllers/concerns/tabs.rb, app/controllers/oecm_controller.rb, app/controllers/wdpa_controller.rb, app/views/oecm/index.html.erb, app/views/partials/tabs/_tabs-thematic-area-database.html.erb, app/views/wdpa/index.html.erb
- Add two extra columns in the comfy CMS for WDPA and OECM Thematic Area page
- [Planner ticket](https://planner.cloud.microsoft/wcmc.onmicrosoft.com/Home/Task/ZJe8gg9tx0aQgY6UxrSFcZcAHc9L?Type=TaskLink&Channel=Link&CreatedTime=638626872948510000)
- Tabs (title) are hidden when no content in them
- It is now on staging server 
- https://pp.new-web.pp-staging.linode.protectedplanet.net/thematic-areas/oecms?tab=OECMs
- https://pp.new-web.pp-staging.linode.protectedplanet.net/thematic-areas/wdpa?tab=Tab5
=> feat: add 2 more tabs

app/models/pame_evaluation.rb
Currently, if a country i,e VAT has no PAs then it is returning all PAME list, so we need to catch this scenario.
[ticket](https://unep-wcmc.codebasehq.com/projects/protected-planet-support-and-maintenance/tickets/351)
=> fix: apply filter to PAME list when a country has no PAs
